# Generated by Django 3.1.1 on 2020-10-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttolapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachmodel',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
