# Generated by Django 3.1.1 on 2020-10-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttolapp', '0002_teachmodel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachmodel',
            name='category',
            field=models.CharField(choices=[('japanese', '国語'), ('english', '英語'), ('society', '社会'), ('math', '数学'), ('physics', '物理'), ('chemistry', '化学'), ('biology', '生物'), ('trivia', '雑学'), ('howtostudy', '勉強法'), ('etc.', 'その他')], max_length=30, verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='teachmodel',
            name='content',
            field=models.TextField(verbose_name='コンテンツ'),
        ),
        migrations.AlterField(
            model_name='teachmodel',
            name='serchword',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='キーワード'),
        ),
    ]
