# Generated by Django 3.1.1 on 2020-11-19 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttolapp', '0003_auto_20201030_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachmodel',
            old_name='serchword',
            new_name='searchword',
        ),
    ]
